### ISSUE TITLE
Version 2.9.25 doesn't work anymore

### ISSUE THREAD

**Issue by dxxvi** [kodi-addons/plugin.video.espn_3#19]
This is what I see in ~/.kodi/temp/kodi.log when I try to "Authenticate with provider to access premium content":
```
15:18:20.353 T:139847725684480   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'simplejson.scanner.JSONDecodeError'>
                                            Error Contents: Expecting value: line 1 column 1 (char 0)
                                            Traceback (most recent call last):
                                              File "/home/ly/.kodi/addons/plugin.video.espn_3/addon.py", line 247, in <module>
                                                regcode = adobe_activate_api.get_regcode()
                                              File "/home/ly/.kodi/addons/plugin.video.espn_3/resources/lib/adobe_activate_api.py", line 124, in get_regcode
                                                resp = get_url_response(url, message, dict(), 'POST')
                                              File "/home/ly/.kodi/addons/plugin.video.espn_3/resources/lib/adobe_activate_api.py", line 78, in get_url_response
                                                return resp.json()
                                              File "/home/ly/.kodi/addons/script.module.requests/lib/requests/models.py", line 896, in json
                                                return complexjson.loads(self.text, **kwargs)
                                              File "/home/ly/.kodi/addons/script.module.simplejson/lib/simplejson/__init__.py", line 488, in loads
                                                return _default_decoder.decode(s)
                                              File "/home/ly/.kodi/addons/script.module.simplejson/lib/simplejson/decoder.py", line 370, in decode
                                                obj, end = self.raw_decode(s)
                                              File "/home/ly/.kodi/addons/script.module.simplejson/lib/simplejson/decoder.py", line 389, in raw_decode
                                                return self.scan_once(s, idx=_w(s, idx).end())
                                              File "/home/ly/.kodi/addons/script.module.simplejson/lib/simplejson/scanner.py", line 119, in scan_once
                                                return _scan_once(string, idx)
                                              File "/home/ly/.kodi/addons/script.module.simplejson/lib/simplejson/scanner.py", line 84, in _scan_once
                                                raise JSONDecodeError(errmsg, string, idx)
                                            JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                            -->End of Python script error report<--
15:18:20.401 T:139848399017472   ERROR: GetDirectory - Error getting plugin://plugin.video.espn_3/?MODE=AUTHENTICATE
15:18:20.402 T:139848399017472   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.espn_3/?MODE=AUTHENTICATE) failed
```

**Comment by awaters1** [comment]
It works for me, can you try again? Sometimes the adobe auth can fail if the system clock is incorrect.

**Comment by dxxvi** [comment]
> Sometimes the adobe auth can fail if the system clock is incorrect
I think that was the case, so I close this issue.
