### ISSUE TITLE
Unicode error causes crash

### ISSUE THREAD

**Issue by kc9jud** [kodi-addons/plugin.video.espn_3#26]
backtrace:
```
2019-09-28 12:15:51.439 T:1582269152   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xfa' in position 139: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.espn_3/addon.py", line 19, in <module>
                                                plugin.run()
                                              File "/home/kodi/.kodi/addons/plugin.video.espn_3/resources/lib/plugin.py", line 133, in run
                                                plugin.run()
                                              File "/home/kodi/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/home/kodi/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/home/kodi/.kodi/addons/plugin.video.espn_3/resources/lib/plugin.py", line 51, in index
                                                legacy.index_legacy_live_events(espn_url)
                                              File "/home/kodi/.kodi/addons/plugin.video.espn_3/resources/lib/ui/legacy.py", line 142, in index_legacy_live_events
                                                _index_event(event, live, upcoming, replay, chosen_sport)
                                              File "/home/kodi/.kodi/addons/plugin.video.espn_3/resources/lib/ui/legacy.py", line 219, in _index_event
                                                'channelResourceId': event.find('adobeResource').text
                                              File "/home/kodi/.kodi/addons/plugin.video.espn_3/resources/lib/item_indexer.py", line 114, in index_item
                                                resource=adobe_rss),
                                              File "/home/kodi/.kodi/addons/script.module.routing/lib/routing.py", line 96, in url_for
                                                path = rule.make_path(*args, **kwargs)
                                              File "/home/kodi/.kodi/addons/script.module.routing/lib/routing.py", line 185, in make_path
                                                query = '?' + urlencode(qs_kwargs) if qs_kwargs else ''
                                              File "/usr/lib/python2.7/urllib.py", line 1343, in urlencode
                                                v = quote_plus(str(v))
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xfa' in position 139: ordinal not in range(128)
                                            -->End of Python script error report<--
```

**Comment by t43pasdf** [comment]
Hi, does it happen with 3.0.1 within the custom repo? https://github.com/kodi-addons/repo.kodi-addons
